pipeline:
  agent:
    any

  environment:
    NODE_VERSION: "14" # Specify the Node.js version
    NPM_VERSION: "latest" # Specify the npm version

  stages:
    - stage: Checkout
      steps:
        - name: Checkout code
          git:
            url: https://github.com/aayushsolanki40/DevOps.git
            branch: main # or specify the branch you want to build

    - stage: Build
      steps:
        - name: Install dependencies
          sh: |
            npm install

    - stage: Test
      steps:
        - name: Run unit tests
          sh: |
            npm run test

    - stage: Deploy
      steps:
        - name: Build and deploy
          sh: |
            npm run build

  post:
    always:
      - cleanWs() # Clean workspace after build

